### ISSUE TITLE
Bitbucket Cloud Personal/Team add-on

### ISSUE THREAD

**Issue by ridaamirini** [agurodriguez/bitbucket-linguist#2]
Hello,

i tried to install the add-on on a team account but i got this error :
 
![bitbucket_error](https://user-images.githubusercontent.com/14841555/35942151-0328f6b0-0c55-11e8-92de-fc0934694d9d.PNG)

Maybe add Team account support or something like this ?

**Comment by agurz** [comment]
Hey @ridaamirini, thanks for reporting this.

I'll definitely investigate on this. I don't know the differences between those kind of accounts but this extension is pretty simple. Maybe there is some stuff with permissions that I should check.

Let you know soon.

**Comment by agurodriguez** [comment]
Hi! Sorry for delay

It should be fixed in the last release
