### ISSUE TITLE
Wrong commit count

### ISSUE THREAD

**Issue by ridaamirini** [agurodriguez/bitbucket-linguist#3]
Hello,

i got the wrong commit number in bitbucket-graphs i have 598 commits and on this addon i have 140 commits.

**Comment by agurz** [comment]
Hey @ridaamirini, thanks for reporting this.

I'll make some tests and see if I can reproduce it.

**Comment by agurodriguez** [comment]
Hi! Sorry for delay

It should be fixed in the last release
